services:
  db:
    image: postgres:16
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=students
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'dslabdb:/var/lib/postgresql/data/'
  spring:
    image: sp
    build:
      context: .
      dockerfile: nonroot-multistage.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/students
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=pass123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3

  frontend:
    #image: front
    build:
      context: https://github.com/gkoulis/ds-lab-2023-frontend.git#main
      #context: git@github.com:gkoulis/ds-lab-2023-frontend.git#env
      #dockerfile: node.Dockerfile
    #    environment:
    #      - VITE_BACKEND=http://spring:9090
    ports:
      - 9000:80
    depends_on:
      spring:
        condition: service_healthy


volumes:
  dslabdb: